name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy test environment variables
        run: |
          cp example.env .env
          sed -i 's/8080/8180/g' .env

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Run dev server
        run: yarn start --sources 'packages/esm-*-app/' --port 8180 &

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:8180

      - name: Run E2E tests
        run: yarn playwright test

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
